Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.ComponentModel

Namespace Amlak.DAL
    <DataObject(True)> _
    Public Class Aparteman
        <DataObjectMethod(DataObjectMethodType.Insert)> _
        Public Shared Function Insert_Aparteman_Foroosh(ByVal UserName As String, ByVal ConuntryID As Integer, ByVal OstanID As Integer, ByVal ShahrID As Integer, ByVal MantaghehID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Price_Kol As String, ByVal Price_Metri As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("UserName", UserName), New SqlParameter("ConuntryID", ConuntryID), New SqlParameter("OstanID", OstanID), New SqlParameter("ShahrID", ShahrID), New SqlParameter("MantaghehID", MantaghehID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Price_Kol", Price_Kol), New SqlParameter("Price_Metri", Price_Metri), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Insert_Aparteman_Foroosh", parameters, RowsAffected)
            Return Result
        End Function

        <DataObjectMethod(DataObjectMethodType.Insert)> _
        Public Shared Function Insert_Aparteman_RahnEjareh(ByVal UserName As String, ByVal ConuntryID As Integer, ByVal OstanID As Integer, ByVal ShahrID As Integer, ByVal MantaghehID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Vadieh As String, ByVal Ejareh As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("UserName", UserName), New SqlParameter("ConuntryID", ConuntryID), New SqlParameter("OstanID", OstanID), New SqlParameter("ShahrID", ShahrID), New SqlParameter("MantaghehID", MantaghehID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Vadieh", Vadieh), New SqlParameter("Ejareh", Ejareh), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Insert_Aparteman_RahnEjareh", parameters, RowsAffected)
            Return Result
        End Function

        <DataObjectMethod(DataObjectMethodType.Insert)> _
        Public Shared Function Insert_Aparteman_Rahn(ByVal UserName As String, ByVal ConuntryID As Integer, ByVal OstanID As Integer, ByVal ShahrID As Integer, ByVal MantaghehID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Vadieh As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("UserName", UserName), New SqlParameter("ConuntryID", ConuntryID), New SqlParameter("OstanID", OstanID), New SqlParameter("ShahrID", ShahrID), New SqlParameter("MantaghehID", MantaghehID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Vadieh", Vadieh), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Insert_Aparteman_Rahn", parameters, RowsAffected)
            Return Result
        End Function

        <DataObjectMethod(DataObjectMethodType.Insert)> _
        Public Shared Function Insert_Aparteman_Ejareh(ByVal UserName As String, ByVal ConuntryID As Integer, ByVal OstanID As Integer, ByVal ShahrID As Integer, ByVal MantaghehID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Ejareh As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("UserName", UserName), New SqlParameter("ConuntryID", ConuntryID), New SqlParameter("OstanID", OstanID), New SqlParameter("ShahrID", ShahrID), New SqlParameter("MantaghehID", MantaghehID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Ejareh", Ejareh), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Insert_Aparteman_Ejareh", parameters, RowsAffected)
            Return Result
        End Function

        '=================================================================================
        '=============================================================================

        <DataObjectMethod(DataObjectMethodType.Update)> _
        Public Shared Function Update_Aparteman_Foroosh(ByVal ID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Price_Kol As String, ByVal Price_Metri As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("ID", ID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Price_Kol", Price_Kol), New SqlParameter("Price_Metri", Price_Metri), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Update_Aparteman_Foroosh", parameters, RowsAffected)
            Return Result
        End Function

        <DataObjectMethod(DataObjectMethodType.Update)> _
        Public Shared Function Update_Aparteman_RahnEjareh(ByVal ID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Vadieh As String, ByVal Ejareh As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("ID", ID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Vadieh", Vadieh), New SqlParameter("Ejareh", Ejareh), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Update_Aparteman_RahnEjareh", parameters, RowsAffected)
            Return Result
        End Function

        <DataObjectMethod(DataObjectMethodType.Update)> _
        Public Shared Function Update_Aparteman_Rahn(ByVal ID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Vadieh As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("ID", ID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Vadieh", Vadieh), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Update_Aparteman_Rahn", parameters, RowsAffected)
            Return Result
        End Function

        <DataObjectMethod(DataObjectMethodType.Update)> _
        Public Shared Function Update_Aparteman_Ejareh(ByVal ID As Integer, ByVal Tel1 As String, ByVal Tel2 As String, ByVal Address As String, ByVal Ejareh As String, ByVal Tozihat_Price As String, ByVal NamaTypeID As Integer, ByVal SokounatStatusID As Integer, ByVal Tedad_Tabagheh As Integer, ByVal Tedad_Vahed As Integer, ByVal Tedad_Khab As Integer, ByVal Vahed_Foroosh As Integer, ByVal Metraj_Mofid As Integer, ByVal Metraj_Mosha As Integer, ByVal Metraj_Kol As Integer, ByVal KarbariTypeID As Integer, ByVal MalekiatTypeID As Integer, ByVal ServiceID As Integer, ByVal AshpazOpen As Boolean, ByVal Ab As Boolean, ByVal Bargh As Boolean, ByVal Gaz As Boolean, ByVal Telphone As Boolean, ByVal Package As Boolean, ByVal Shoofaj As Boolean, ByVal Espilet As Boolean, ByVal Shoomineh As Boolean, ByVal Anbari As Boolean, ByVal Parking As Boolean, ByVal Asansor As Boolean, ByVal Dar_Kontroli As Boolean, ByVal Tozihat As String, ByVal AgahiTitle As String) As Integer
            Dim RowsAffected As Integer = 0
            Dim Result As Integer = 0
            Dim dbo As DbObject = New DbObject()
            Dim parameters() As SqlParameter = New SqlParameter() {New SqlParameter("ID", ID), New SqlParameter("Tel1", Tel1), New SqlParameter("Tel2", Tel2), New SqlParameter("Address", Address), New SqlParameter("Ejareh", Ejareh), New SqlParameter("Tozihat_Price", Tozihat_Price), New SqlParameter("NamaTypeID", NamaTypeID), New SqlParameter("SokounatStatusID", SokounatStatusID), New SqlParameter("Tedad_Tabagheh", Tedad_Tabagheh), New SqlParameter("Tedad_Vahed", Tedad_Vahed), New SqlParameter("Tedad_Khab", Tedad_Khab), New SqlParameter("Vahed_Foroosh", Vahed_Foroosh), New SqlParameter("Metraj_Mofid", Metraj_Mofid), New SqlParameter("Metraj_Mosha", Metraj_Mosha), New SqlParameter("Metraj_Kol", Metraj_Kol), New SqlParameter("KarbariTypeID", KarbariTypeID), New SqlParameter("MalekiatTypeID", MalekiatTypeID), New SqlParameter("ServiceID", ServiceID), New SqlParameter("AshpazOpen", AshpazOpen), New SqlParameter("Ab", Ab), New SqlParameter("Bargh", Bargh), New SqlParameter("Gaz", Gaz), New SqlParameter("Telphone", Telphone), New SqlParameter("Package", Package), New SqlParameter("Shoofaj", Shoofaj), New SqlParameter("Espilet", Espilet), New SqlParameter("Shoomineh", Shoomineh), New SqlParameter("Anbari", Anbari), New SqlParameter("Parking", Parking), New SqlParameter("Asansor", Asansor), New SqlParameter("Dar_Kontroli", Dar_Kontroli), New SqlParameter("Tozihat", Tozihat), New SqlParameter("AgahiTitle", AgahiTitle)}

            Result = dbo.RunProcedure("sp_tblMelk_Update_Aparteman_Ejareh", parameters, RowsAffected)
            Return Result
        End Function

    End Class
End Namespace